### PR TITLE
Java Code that doesn't work

### PR DESCRIPTION
**Pull request by ajaygupta3**
@twang This is a small bit of java code that won't complete the desired outcome.

### CODE REVIEW

**Comment by twang** [comment]
@ajaygupta3 can you make sure that you've included the java file? Take a look back at the directions and that you'e saved the .java file in the right place and then push it

**Comment by ajaygupta3** [comment]
@twang V2- now should be a java file

If the file (FirstJCode.java) doesn't appear in the folder please let me know - I have it saved on my desktop as a java file in Documents -> GitHub -> unit1 work in progress

**Comment by twang** [comment]
@ajaygupta3 hmm... can you make sure you've committed the change and then pushed it? See steps 9 and 12 on the doc

**Comment by twang** [comment]
Any luck @ajaygupta3?

**Comment by ajaygupta3** [comment]
image

@twang it shows my code is under the assignment, from your end is it not accessible?

**Comment by twang** [comment]
I can see it, but we wanted to do what you did in the essay https://github.com/twangcs/cs-essay-1-ajaygupta3/pull/1 where the changes show up in this pull request. Don't want to upload files in the future

**Pull request closed without merging**
